# ---------------------------------
# Maestri binary module SConscript 
# ---------------------------------

# USER DEFINED >>
binmod_src = Split("""
    main.cpp
    """)
# << 

Import( ['env', 'mod', 'packagelibpath', 'packagebinpath', 'packagebuildroot'] )

modenv = env.Clone()
modenv.Append(LIBS = ['ModuleOne', 'ModuleTwo'])

binmod_bin = modenv.Program( target = mod, source = binmod_src) 
binmod = modenv.Install( packagebinpath, binmod_bin )

Return( ['binmod'] )
